# Generated by Django 5.0.6 on 2024-06-03 16:56

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_name', models.CharField(max_length=200)),
                ('product_subname', models.CharField(max_length=200, null=True)),
                ('product_type', models.CharField(max_length=200)),
                ('mrp', models.DecimalField(decimal_places=2, max_digits=8)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('product_description', models.TextField(blank=True)),
                ('product_image', models.CharField(max_length=255)),
                ('product_size', models.CharField(max_length=5)),
                ('product_color', models.CharField(max_length=25)),
                ('product_gender', models.CharField(max_length=1)),
            ],
        ),
    ]
