# Generated by Django 5.0.6 on 2024-06-03 17:17

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0003_alter_product_product_type'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product_gender',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_gender_name', models.CharField(max_length=1)),
                ('product_gender_desc', models.CharField(max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='Product_size',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('product_size_name', models.CharField(max_length=5)),
                ('product_size_desc', models.CharField(max_length=30)),
            ],
        ),
        migrations.AlterField(
            model_name='product',
            name='product_gender',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product_gender'),
        ),
        migrations.AlterField(
            model_name='product',
            name='product_size',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.product_size'),
        ),
    ]
