# Generated by Django 5.0.6 on 2024-07-08 09:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0015_order'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Order',
        ),
    ]
