# Generated by Django 5.0.6 on 2024-07-08 09:36

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0016_delete_order'),
    ]

    operations = [
        migrations.RenameField(
            model_name='product',
            old_name='color',
            new_name='product_color',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='description',
            new_name='product_description',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='gender',
            new_name='product_gender',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='image',
            new_name='product_image',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='name',
            new_name='product_name',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='size',
            new_name='product_size',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='subname',
            new_name='product_subname',
        ),
        migrations.RenameField(
            model_name='product',
            old_name='type',
            new_name='product_type',
        ),
    ]
